version: 2
updates: 
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: -1

  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: -1
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "npm"
    directory: "/demos/esm-dev-app"
    open-pull-requests-limit: -1
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "npm"
    directory: "/docs/document"
    open-pull-requests-limit: -1
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "npm"
    directory: "/docs/document/website"
    open-pull-requests-limit: -1
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    target-branch: "v0_dev"
    open-pull-requests-limit: -1

  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: -1
    schedule:
      interval: "weekly"
      day: "sunday"
    target-branch: "v0_dev"